/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import model.Password;
import controler.ApplicationData;
import debug.D;
import javax.swing.JOptionPane;

/**
 *
 * @author tony
 */
public class NewPassDialog extends javax.swing.JDialog {
    private Password pass;
    private final String dialogTitle;
    private int index;
    private final ApplicationData appData=ApplicationData.getAppData();
    private String titleInicial;

    /**
     * Creates new form NewPassDialog
     * @param parent
     * @param modal
     * @param dialogTitle
     */
    // using for new
    public NewPassDialog(java.awt.Frame parent, boolean modal, String dialogTitle) {
        super(parent, modal);
        initComponents();
        setLocation(320,0);
        setTitle(dialogTitle); 
        this.dialogTitle=dialogTitle;
        this.txtTitle.setText("");
        this.txtUser.setText("");
        this.txtPass.setText("");
        this.txtSite.setText("");
        this.txtAreaNote.setText("");   
        
        D.deb(dialogTitle);
        D.deb("para new...");
    }
    // using for edit
    public NewPassDialog(java.awt.Frame parent,
                boolean modal,
                String dialogTitle, Password pass, int index) {
        super(parent, modal);
        initComponents();
        setLocation(320,0);
        setTitle(dialogTitle);
        this.dialogTitle=dialogTitle;
        this.pass = pass;
        this.index=index;
        txtTitle.setText(pass.getTitle());
        txtUser.setText(pass.getUser());
        txtPass.setText(pass.getPass());
        txtSite.setText(pass.getSite());
        txtAreaNote.setText(pass.getNote());
        titleInicial = "".concat(pass.getTitle());
        
        D.deb(dialogTitle);
        D.deb("para edit...");
        D.deb(index);
        
    }
    
    private Password createPassword(){
        Password password = new Password();
        password.setTitle(txtTitle.getText());
        password.setUser(txtUser.getText());
        password.setPass(txtPass.getText());
        password.setSite(txtSite.getText());
        password.setNote(txtAreaNote.getText());
        
        return password;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTitle = new javax.swing.JTextField();
        txtUser = new javax.swing.JTextField();
        txtPass = new javax.swing.JTextField();
        txtSite = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaNote = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnAceitar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setMinimumSize(new java.awt.Dimension(315, 380));
        jPanel1.setVerifyInputWhenFocusTarget(false);

        jLabel3.setText("Pass:");

        jLabel4.setText("Sitio:");

        jLabel5.setText("Nota:");

        txtTitle.setText("jTextField1");

        txtUser.setText("jTextField2");

        txtPass.setText("jTextField3");

        txtSite.setText("jTextField4");

        txtAreaNote.setColumns(20);
        txtAreaNote.setLineWrap(true);
        txtAreaNote.setRows(5);
        jScrollPane1.setViewportView(txtAreaNote);

        jLabel6.setText("Título:");

        jLabel7.setText("User:");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnAceitar.setText("Aceitar");
        btnAceitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceitarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(269, 269, 269))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAceitar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSite, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtPass, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtUser, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtTitle, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnAceitar)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAceitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceitarActionPerformed
        // TODO add your handling code here:
        if (!(txtTitle.getText().equals("")) ){//&& titleValid()
            //ApplicationData appData = ApplicationData.getAppData();
            if (this.dialogTitle.equals("Nova password...")){
                if (titleValid()){
                    appData.addPasswords(createPassword());
                    this.setVisible(false);
                }else{
                    JOptionPane.showMessageDialog(null, "Este título já existe!");
                }             
            }
            if (this.dialogTitle.equals("Editar password...")){
                if (titleValid_2()){
                    //appData.setEditPassword(this.index, createPassword());
                    appData.removePasswords(pass);
                    appData.addPasswords(createPassword());
                    this.setVisible(false);
                }else{
                    JOptionPane.showMessageDialog(null, "Este título já existe!");
                }
            }                        
        }else{
            JOptionPane.showMessageDialog(null, "Não têm titulo!");
        }        
    }//GEN-LAST:event_btnAceitarActionPerformed

    private boolean titleValid(){
        boolean valid = true;
        for(Password p: appData.getPasswords()){
            if (p.getTitle().equals(txtTitle.getText())) valid=false;            
        }
        return valid;
    }
    
    private boolean titleValid_2(){
        boolean valid = true;
        int num = 0;
        
        for(Password p: appData.getPasswords()){
            if (p.getTitle().equals(txtTitle.getText())){
                num++;                
            }            
        }
        
        if (titleInicial.equals(txtTitle.getText())){
            //não houve alteração do titulo
            if (num>1)valid=false;
        }else{
            //houve alteração
            if (num>0)valid=false;
        }
        
        return valid;
    }
    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceitar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAreaNote;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtSite;
    private javax.swing.JTextField txtTitle;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
